### ISSUE TITLE
Keys only shuffle three times before app freezes

### ISSUE THREAD

**Issue by Dead-Vortex** [etherealxx/limbo-godot#1]
https://github.com/etherealxx/limbo-godot/assets/118923239/17dbc112-7f31-46f8-a466-3f8e0f748a97

**Comment by blackm1n** [comment]
Had the same issue. Fixed it by turning 16:9 resolution on and transparent background off in the settings, however I feel like that's a band-aid solution and may not work for you.

**Comment by superkuzia15** [comment]
yeah, changing both of those settings didn't work. it feels like pure luck whether i'll be able to play this or not

**Comment by etherealxx** [comment]
thanks both of you three for reporting, i'm aware of this bug, but i'm not sure what caused it, and i can't replicate it on my device. It might have something to do with the processor, like faster processor have lower chance of this occurring (though my processor is just i3 12100f, still better than some old laptop processor though). As far as i'm aware, transparency makes a lot of calculation in the background which might slows things down.
So the way the shuffle works is that first it queues all of the pattern, then it tells all the keys to do the first shuffle. then there's a timer every 0.5 second to check if every key has done it's first shuffle (aka moved to the correct position based on the queued pattern). If yes, then do the next shuffle, if not, wait for every key to finish it's first shuffle, which might be what happening here.
I'll look forward into this.

**Comment by CarelessSoul** [comment]
Adding further to this, it seems like having my monitor set to 144hz causes this to happen, but any others (165, 120, 60) work fine for whatever reason

**Comment by etherealxx** [comment]
@CarelessSoul could you please try this one, open settings menu (double right click on a key), make sure physics timer is on, save and relaunch, and see if the problem persist in 144hz?
[Uploading limbo_keygen2.zip…]()

**Comment by etherealxx** [comment]
@CarelessSoul could you please try this one, open settings menu (double right click on a key), make sure physics timer is on, save and relaunch, and see if the problem persist in 144hz?

[limbo_keygen2.zip](https://github.com/etherealxx/limbo-godot/files/15084594/limbo_keygen2.zip)

**Comment by etherealxx** [comment]
Hello everyone. I released a new patch, it should fix the shuffle freezing problem, and some other bugs.
https://github.com/etherealxx/limbo-godot/releases/tag/v1.2.0
Feel free to open this issue if the same bugs still happens on your side.✨
