### ISSUE TITLE
How do I make it work on mobile

### ISSUE THREAD

**Issue by ImmediateMurderProfessionals** [etherealxx/limbo-godot#4]
How do I make it work on mobile

also please ask @GDColon to unblock me

**Comment by etherealxx** [comment]
There are several things that makes this won't work on mobile:

- Currently there's no way to make transparent window in Godot (the engine that i use) for Android, so the keys will have like black background on it
- There's no way of using windows in Android. You know, like those window on your Windows 11 desktop that you can move around, it isn't possible in Android
- So without transparency and windows, it'll be just like a regular android app, nothing special, worthless for just a funny key game, would be uninstalled after being played a few times. Also at that point just play some limbo copies on the actual geometry dash, there are plenty

Idk why Colon blocked you though, don't randomly tag ppl like that btw.
I'm not affiliated with him whatsoever.

**Comment by ImmediateMurderProfessionals** [comment]
I'm on IOS

**Comment by etherealxx** [comment]
> I'm on IOS

It's even harder for me lol. I need mac device to export to iOS, and ios has more strict rules compared to android, so no shot

**Comment by ImmediateMurderProfessionals** [comment]
> > I'm on IOS
> 
> It's even harder for me lol. I need mac device to export to iOS, and **ios has more strict rules compared to android**, so no shot

Yeah fuck Apple. I hate not being allowed to use nong hacks in GD on IOS.
