### ISSUE TITLE
Amaising 

### ISSUE THREAD

**Issue by Mrgaton** [etherealxx/limbo-godot#8]
if you minimize the window of the corect key you can esaly cheat it

**Comment by Mrgaton** [comment]
also you could try to use upx to compress the binary itself

**Comment by etherealxx** [comment]
Yeah as reported in https://github.com/etherealxx/limbo-godot/issues/5. The current issue lies on how Godot handles unfocusable windows, so i can do nothing with it, i guess. I reported the [bug](https://github.com/godotengine/godot/issues/91711) to the godot source issue page but no further action so far.

also i can't use upx, tried it. maybe exes made with godot can't.
![image](https://github.com/user-attachments/assets/966ca156-7980-4b51-a7c5-98fb7b7a235b)
